language: minimal
sudo: required

before_install:
  - chmod +x $GPG_DIR/deploy_npm
  - chmod +x $GPG_DIR/deploy_maven
  - export PATH=$PATH:$GPG_DIR

jobs:
  include:
    - script: echo "job 1"
    - script: echo "job 2"

    # - name: Job java maven plugin
    # language: java
    # jdk: openjdk8
    # addons:
    #   apt:
    #     packages:
    #       - graphviz
    # script: mvn install -Dgpg.skip -Dmaven.javadoc.skip=true -B -V -U
    # cache:
    #   directories:
    #     - '$HOME/.m2'
    # after_success:
    #   - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
    #   - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
    # deploy:
    #   provider: script
    #   script: deploy_maven
    #   skip_cleanup: true
    # - name: Job typescript plugin
    # language: node_js
    # node_js:
    #   - "node"
    # before_script:
    #   - cd livingdoc-typescript-plugin
    # install: npm install
    # script:
    #   - npm test
    #   - npm run build
    # deploy:
    #   provider: npm
    #   email: "YOUR_EMAIL_ADDRESS"
    #   api_key: "YOUR_AUTH_TOKEN"
    #   script: deploy_npm

env:
  global:
    - GPG_DIR="`pwd`/.travis"
    - secure: llf7R4RqxrKbM0CDpgAu38bt3ojrPeWbUq/9K8xN4UDCa7FOlbUx5/vlpDzaHSZlW2G04pl1lHjH+Wq9IultDrY7/FmWs8hGrNwEg8ZBKiz9ydImJzgMoJGfjlIgtlLaIksxdU4GesGPehUrk65uyoI2dCsQLunOX5nF9tnbrBcOzg8NngHEp6/p13P07C+ls3XBmTtgbelGTyRG4A1IHXqonwQnhfJyfHOY0nx7IwHnFviK0docJCWq2XWg2XfOHJBtOCS1iQYIoxNEd75M47T9sbir6j5PORV0Y+sGAas8yuAEJvSpwJicWiCMNWTKu06DCZLu3IqMMmS7Mahe77n5R17Eo1MfrIAp/jYj8DpI8vzikaSUxaP8lu3HHSBsEaDq0Q9NgeA0xUi7jbmrMHHJWy9GXxRhK2LOL9mVxYf2a4Lv9qaGeNhxnpggJmBgAjWATatpBwwk/tRlyV79XNgFXXXbU3q7YXGodIDdwQDTcTUqZ9SaP/lGq5Vw4lji1Rosvv8Nfhgoeddxq6I6X1brV6qihn2AFEPmY6lQ+BvW9/QGyjEmtzAK90QsBszNTFQ+HjjAbDcZ5ZqRO6sFM5LL4r8Zd6bwKWE3GruVAcRZ56jfQ0skfBDiPbEwFlxIesG+Ov+qRB1Lh1bSNHkn194JwSvFmRRrgT3VvC7geAg=
    - secure: fNCN2chRkI2DOqNNKs2rxe16mMSovgCKlGtSCu3o7l+hWMRUWeX6LkUvVmV7Jcdz0t4zY6t1H3XtvSM6dZYs9/JCQLXfZGsoonDsClDIVrjOQNF5jFTvQpgdilTq6PowKqiNFO9GvH1C+e0RFyPYp7YetBpaBjGooGx76vTnFfYliUs/EqfWHJhPeA5Uz/Jnx8ayDZLCF5EG6KoSiWS1jOhxAB15L/ei0LVqf0MDzAm9lC+y0kL/ATrEvvBYWuhxY6revS3QWTsB3A5jf7OfvrP3Ii1YQutuUX8SFsjeko8Y3oDCslQ29L3PByJ1gr1hIHQsuYZKKDnZJLhy01NfFccIyITll/bPZJ1sTFUO3IXkBQ0pWwP04Q3CyRugF+DqLAve0iZe+rVwf4hdbBt6/7DspW2ggPq2DbA0pNH+9Db1Dcj/K+O1ldUyFIhpi3Ui0y/FaExL/wasgLsRdGt/92UsVDZjS1DUT3RnVLep9JrvEXLnaf3tJD2p2H8P7YdyR8z036tVotx/3XkZrEu++x1sxy0O2CMuKwyt8lK4YozlepQd98bntr/BpmDJ7rrnNu//vXjwAlNd9PIowHqPdk5W3a52SBPphZvJUc2LWd+KhNlhHI4FMtEIWhKB8oNyWNn0S15jWaXaUtRVGRRqcJneg3e9REr0oX+SaW0Sl2c=
    - secure: bn9fF+BJdxDzsBLMAhHaK5GhDmmRg0nRtRIIDTstPTen+4gskEo/YesA8TV95bExt+1yBWn7xUA7I4vmu9Cn+SIQJb68EuRBSTyKtTtLkMBIwVYBoepmfABZl6cT/DQjafuSKWwIFCmsCpYFAisrGqPVhx7zGKROPdaEM/+RFHmosHkNkP4K3nXaQvyC7TufeaCcORV5mg6L1Vx2fnBzoszkxOjwYSm4e3XWsXtk5xlNBNxlUaBfcxjJwQClzB1JyAmluj0t2q7IK+IsNm5fqeoRABM4o2pE7CfVAqmhOv9oNu4V6g37kTGzUxPzIPCHXRhJapWLgiIxIvloS7A/euDBj/ItbDwi0AYw06uasigZIuY7m8rCofuzyfbu7IhCWva++tXUqvVH0tlBEN5ICIyxPNIZ3e+pOwHTL249cITdACRK2ZzuGQLP1/EZSXN03hwLZpWaUNiXAqAkR45iVBiEVZv8vqvPHaSGAkHSne49MqFB6oyzAliyhDlWHdUyusWhl8HXHXSO5apX6grby38uOexqV/M1Ri9oggG7FYTlQivEbuhqAq41bVZtDC0fZmumQ4PAMY7vrNPl1o2PbyOFK46D8pQR3Uof4+nvwKHASgX221CwjYcn+W5uIFffkg5DaVYmPn12GbfQkjx6iJRgn9FsamgGrtrakg5prmQ=
    - secure: aTHUOAxZzwDrVz0e9B9xJSPBp9zVza3E73WHiyDzsL5j+mAYhiiyeDVLMLlDp0pPOiuds3K1UnSnqaOqJT8C4EWLdhae/TVG2K3jieawbTvPCj3m5Hwqd90wnlPTXM/uwXEtF7yNKib7pmhULzQckQvuGR5SmgbuqfQ13S4AIc3S69xUSNOPXn1LbcCYpzss/Yt6qGrRXJFbgga5hLLLHKL/x7KvMdsjSS3uv2UxJGpvys4UGMx+c5/uHRVTF2Cb1kJ6e8RqVxaDBU/SyS9F/oHJYhF004j2NbnUm8X3HL1W9Vuy5npMIOkyajcwUuIISAIbcTqGkVVIF+rLpRmM7pWlcWde9/Dwpy84+xzaIkw3dDckOLquagBLx8dE/qbcaXbcCyIKTNRBSPqDncguzXLhuffkfKDThZHDuN0al12BBEvazHtWPaghNUfu3dJSiU/5doY8PYpkAHQPt2RjK4YIGqI4jih0XEkDgF63roNHoQttWLOE5FVmGHdGO/qIk/p0cDo/5UYTBcLwDXBLDZxATWF7nupFPMo82s3RC/ZPkt7/+gCqDv44jFaF88TxrTxCdEMzrNTEljY67Rr9y42Xknbo+lEuRAfxHMrb5I8reeyPexsIcEPBN6SSLY5l8Z7Cc3oIWcL15tn1SrJBhmys4RgNsWI6CeVHdIYelQ4=
    - secure: fc5vZkD60K68Mp/B1teDqU1P3dJ153CFT9FqLLQ+q8VJ1keJby+cfkQgrbZ/RtEW6UoobvXTRZjj1l17T77nsxCaKwoDNPeZkiPmQW9be7bwNOk+9IJHXupNmYiqkVSmlN/PWkBdR95X7fWAN6rQ7i5OVo6kxIgHAOcO/ZzvfKDR9DXG5VWgfs58MeSezrjxI/ExI+x2z43V70gdWz1XW8isysBJ1tET9mVaZ55nfFtUjCihoqnL03R94QwP1jX6m2tVRz5CGaNtX0o+iIZ3uHPIzeYZE7NPtpiQ3JLdXKYWs1ApKenqvGqNcez6fI69dyYWqORL6wEqz/8EVMD6bp+dsLFGQiqvSa2lzB7eHBLoLt6iGzpSlg++ZWv9GHdi0lP1H7mCHGLNa/0HFf5cayNme0ZAQzXsJDC3XyLMCluPGWzrgjU+8kSA3M9EU+DF+QPUsS6gDFRmYRefc2rh+pm+rF3HWdVKjhULgr3vTAVWZeGHHFvy5DTC72bXy3aYswf8bbvz4hORsC3ZVBXL+ZqqWU6VPMW1LJxn+1xpmCVTOA6BVcq8iBn7lHO8X7HFG5nZGZSWsR9xva3X8jD4lto296/Ca1DmLXlt7028xsoje6aXm4ylDEUJQTeikXUX9RFbR3BzZ30cnZh9wsxsMdt/rJ6JyYppLgmqBoLW8Vg=
    - secure: V3+qzEX/fZ7LiLzce9T3bbMHW6FFp2LiJlRKuMNgn5l84A9hCI1puUnSO1e2+6t1O0ddgzMzOSUI/FVT6kAWMOJrafNNHAkDCCIkVC92l2DHEgHI8PQNUn4sOfQNhcbTayymtQjG5AxpQZkyohjydFewrSKwcQ/T3cNRPFBdswhlXxqk2zqcBMqyc4Bgjr0ZFqFEtci1uHKQ7+6HnL1fqGH7wIXVmvkS+C2mlUlNG3Vzq8SUC+gXXb6kMqjPywxQU6bXc7eyvj5JYSHVVsXcAy5XkMaq8YrrKcefttImLqAfYGjWrllLli9FNDVpzLIWmsrAxJBSKM4nw4DkZkwpCbRchNy2MQLqTSJF8ElskJe5dvQfoRXtVxucJqyOdRj1KurURUy3HoHMCHHd2yyO+9Pdyu3IbSD1gxNpJEtqAoFWdp2mlE+gLG5ULnAN0wafQyNhOsfMo8bCnQ7B4paMmHEhRfpmuVi2TQnM+JIzPBPC3RJjfzCXROOolCelQAj2SUotIqZ08fCHQ7xzsAoUQAwLwOvgE53j+bQQTzLHanNApekLhW9EUPpB+jO1bUqY0s/XH1HxDTgk9bEUDqiOI3Kt5eu4TX2pCVw3JnDkwiehUhP2Q9WYZjwzp8AlskBQYvYP35X7LaZuMy16B4R23vh9ttqOM1HzfWOHEjt0MaE=

branches:
  only:
    - master

notifications:
  email:
    - julienboz@gmail.com
  on_success: change
  on_failure: always
